apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: deployment
        image: public.ecr.aws/r9h7w4o2/deployment:latest
        ports:
        - containerPort: 3000
