name: Terraform Workflow

on:
  push:
    branches:
      - dev # Change this to the branch you want to trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.2 # Update to your desired Terraform version

    - name: Initialize Terraform
      run: terraform init
      working-directory: ./

    - name: Plan Infrastructure
      run: terraform plan -out=tfplan
      working-directory: ./

    - name: Apply Infrastructure
      run: terraform apply -auto-approve tfplan
      working-directory: ./
